name: Build

on:
  workflow_dispatch:
    inputs:
      bump_version:
        type: choice
        description: Bump version
        options:
          - patch
          - minor
          - major
        default: patch
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci

      - name: Build
        id: build
        run: ./scripts/build.sh
        shell: bash
        env:
          BUMP_VERSION: ${{ github.event.inputs.bump_version }}

      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RMG_NPM_PUBLISH }}
