name: Build

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci

      - name: Build
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh
        id: build

      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RMG_NPM_PUBLISH }}
